class EvidenceGraph:
    """
    Standardized graph repository of sensory evidence nodes generated by runtimes.
    """
    def __init__(self):
        self.nodes = {}

    def add_node(self, runtime_id: str, observation: str, confidence: float, evidence_details: list, cost: float = 1.0, dependencies: list = None) -> dict:
        node_id = f"ev_{runtime_id}_{observation.lower()}"
        node = {
            "id": node_id,
            "runtime": runtime_id,
            "observation": observation,
            "confidence": float(confidence),
            "evidence": evidence_details,
            "cost": float(cost),
            "dependencies": dependencies if dependencies else []
        }
        self.nodes[node_id] = node
        return node

    def get_node(self, node_id: str) -> dict:
        return self.nodes.get(node_id)

    def get_all_nodes(self) -> list:
        return list(self.nodes.values())

    def get_evidence_by_runtime(self, runtime_id: str) -> list:
        return [node for node in self.nodes.values() if node["runtime"] == runtime_id]

    def get_evidence_by_observation(self, observation: str) -> list:
        return [node for node in self.nodes.values() if node["observation"].lower() == observation.lower()]
